
// client SENDS to server
module.exports.ACTIONS = {
  TURN_RIGHT_BEGIN: 'TURN_RIGHT_BEGIN',
  TURN_RIGHT_STOP: 'TURN_RIGHT_STOP',
  TURN_LEFT_BEGIN: 'TURN_LEFT_BEGIN',
  TURN_LEFT_STOP: 'TURN_LEFT_STOP',
  THRUST_FORWARD_BEGIN: 'THRUST_FORWARD_BEGIN',
  THRUST_FORWARD_STOP: 'THRUST_FORWARD_STOP',
  THRUST_BACKWARD_BEGIN: 'THRUST_BACKWARD_BEGIN',
  THRUST_BACKWARD_STOP: 'THRUST_BACKWARD_STOP',
  SHOOT_MAIN_BEGIN: 'SHOOT_MAIN_BEGIN',
  SHOOT_MAIN_STOP: 'SHOOT_MAIN_STOP',
  GRAPPLE_GUN_RELEASE: 'GRAPPLE_GUN_RELEASE',
  GRAPPLE_GUN_START: 'GRAPPLE_GUN_START'
};

// client RECEIVES from server
module.exports.EVENTS = {
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_DIED: 'PLAYER_DIED',
  PLAYER_SPAWNED: 'PLAYER_SPAWNED',
  PLAYER_MESSAGED: 'PLAYER_MESSAGED'
};

module.exports.ENTITY_TYPES = {
  PLAYER: 'PLAYER',
  PLANET: 'PLANET',
  BULLET: 'BULLET',
  SPRING: 'SPRING'
};

module.exports.KEY_BINDINGS = {
  TURN_RIGHT_BEGIN: ['D'],
  TURN_RIGHT_STOP: ['!D'],
  TURN_LEFT_BEGIN: ['A'],
  TURN_LEFT_STOP: ['!A'],
  THRUST_FORWARD_BEGIN: ['W'],
  THRUST_FORWARD_STOP: ['!W'],
  THRUST_BACKWARD_BEGIN: ['S'],
  THRUST_BACKWARD_STOP: ['!S'],
  SHOOT_MAIN_BEGIN: ['<space>'],
  SHOOT_MAIN_STOP: ['!<space>'],
  GRAPPLE_GUN_RELEASE: ['E'],
  GRAPPLE_GUN_START: ['Q']
};

module.exports.MESSAGE_TEMPLATE = {
  PLAYER_JOINED: 'Player %PLAYER% has joined.',
  PLAYER_LEFT: 'Player %PLAYER% has left'
};

module.exports.SERVER_SETTINGS = {
  STEP_INTERVAL: 30
};

module.exports.GAME_SETTINGS = {
  PLAYER_MAX_SPEED: 20,
  BASE_PLAYER_THRUST_ACCELERATION: 0.3,
  BASE_PLAYER_TURN_ACCELERATION: 5,
  BASE_DEFAULT_TURN_ACCELERATION: 0,
  BASE_PLAYER_BULLET_DAMAGE: 10,
  BASE_PLAYER_BULLET_LIFETIME: 4,
  BASE_PLAYER_BULLET_SPEED: 30,
  BASE_PLAYER_FIRERATE: 0.2
};